language: ruby

# don't require sudo for installs
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

before_install:
    gem install bundle travis

script:
  - "scripts/pre-commit"

