# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.
# See https://jekyllrb.com/docs/configuration/ for docs

# Site settings, accessible through {{ site.<variable> }}
lang: "en"
title: the website of jyn
email: jyn514@gmail.com
author: jyn
description: i write about code, and things that bring me joy, and sometimes other things too
baseurl: ""
resume: Resume.pdf
github_username:  jyn514
linkedin_username:  jynelson514
public_key: E655823D8D8B1088
timezone: America/New_York

collections:
    talks:
        output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "jyn"
      audience: "everyone"
  - scope:
      path: ""
      type: "talks"
    values:
      author: "jyn"
      audience: "developers"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - scripts
    - vendor

include:
    - .well-known
