#!/bin/sh

if [ $# -lt 1 ]; then
	echo "Usage: $(basename "$0") title"
	exit 1
fi

cd /usr/local/src/second-website/_posts
file="$(date -I)-$(echo $@ | tr ' ' '-').md"
{ echo '---
layout:	post'
echo "title:	\"$@\""
echo "$(date "+date:%t%Y-%m-%d %T %z")"
echo "excerpt:"
echo '---'
} >> "$file"

echo Created new post at $file
