#!/bin/sh

if [ $# -eq 0 ]; then
	echo "Usage: $(basename "$0") title"
	exit 1
fi

set -u  # undefined variables are an error

cd "$(dirname "$(realpath "$0")")/../_posts"

TITLE="$(echo $@ | tr '\t \r' '---' | tr -d '\n!,?:').md"
TIME="$(date "+%Y-%m-%d %T %z")"
FILE="$(date -I)-$TITLE"
FORMAT="---
layout:	post
title:	\"$@\"
date:	$TIME
audience: everyone
excerpt:
---
"

ls --quoting-style=shell-escape | grep -- "-$TITLE$" > /dev/null
GREPSTATUS=$?

touch $FILE || { echo "$FILE is not writable"; exit 1; }

if [ "$GREPSTATUS" -eq 0 ]; then
	printf "file titled $TITLE exists, updating date... "
	if ! [ -e "$FILE" ]; then mv -f *"-$TITLE" "$FILE"; fi
	sed -i "s/date:	.*/date:	$TIME/" $FILE
	echo Success
else
	echo Creating new post at $(realpath $FILE)
	echo "$FORMAT" >> "$FILE"
fi

exit 0
