#!/bin/sh

set -v

add () {
	FAILED="$(echo "$FAILED + $1" | bc)"
}

FAILED=0

bundle exec jekyll build

# does NOT currently exit with errors
# travis doesn't recognize apt: for some reason
cd "$(git rev-parse --show-toplevel)"
travis lint --skip-completion-check
add $?

# Linkedin blocks robots
bundle exec htmlproofer \
	--url-ignore https://www.linkedin.com/in/joshuayn _site ./_site
add $?

linklint -error -warn -net -root ./_site /@
add $?

if [ "$FAILED" -ne 0 ] ; then
	echo "Commit had $FAILED errors"
else
	echo "Commit succeeded"
fi

exit $FAILED

