#!/bin/sh

add () {
	FAILED="$(echo "$FAILED + $1" | bc)"
}

FAILED=0
# Linkedin blocks robots
# prefetch fails if DNSSEC available
# localhost is not a link, it just looks like one
# others aren't checked properly by travis
IGNORED=$(echo '
http://prefetch.validatorsearch.verisignlabs.com,
https://www.linkedin.com/in/joshuayn,
/localhost/,
https://danluu.com/octopress-speedup/,
https://haveibeenpwned.com/,
https://openkeychain.org/,
https://emailselfdefense.fsf.org/en/,
' | tr -d '\n')

cd "$(git rev-parse --show-toplevel)"
if ! bundle exec jekyll build; then
   echo "PANIC: Failed to build site"
   exit 1
fi

# does NOT currently exit with errors: travis doesn't recognize apt for some reason
travis lint --skip-completion-check
add $?

bundle exec htmlproofer \
	--url-ignore "$IGNORED" \
	--check-favicon --check-html --report-missing-names --report-script-embeds \
	./_site
add $?

linklint -error -warn -net -root ./_site /@
add $?

if [ "$FAILED" -ne 0 ] ; then
	echo "Commit had $FAILED errors"
else
	echo "Commit succeeded"
fi

exit $FAILED

